name: onboarding_flow
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper : any
  firebase_auth: ^0.16.0
  flutter_facebook_login: ^1.1.1
  shared_preferences: any
  google_maps_flutter: ^0.5.26+4
  cloud_firestore: ^0.13.5
  cached_network_image: ^2.0.0
  fluttertoast: any
  flutter_google_places: ^0.2.4
  location: ^3.0.2
  upgrader: any
  http:
  firebase_analytics: ^5.0.11
  webview_flutter: ^0.3.19+9
  flutter_webview_plugin: "0.3.0+2"
  nice_button: ^0.1.7
  package_info: ^0.4.0+16
  awesome_dialog: "0.1.3"
  device_id: "0.2.0"
  launch_review: ^1.0.1
  emoji_feedback: "0.1.0"
  flutter_xlider: "3.3.1"
  search_widget: "1.0.2"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default.png
    - assets/berlin.png
    - assets/delhi.png
    - assets/london.png
    - assets/newyork.png
    - assets/paris.png
    - assets/newicon.png
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/slide4.png
    - assets/images/slide5.png
    - assets/headericon.png
    - assets/plus.png
    - assets/topic_one.png
    - assets/topic_two.png
    - assets/topic_three.png
    - assets/topic_four.png
    - assets/topic_fie.png
    - assets/topic_six.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
